on:
  push:
    branches: [main, master]
    tags: ['*']

name: pkgdown

permissions:
  contents: write
  actions: read

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: '4.1.1'

      - name: Install dependencies
        run: |
          install.packages('remotes')
          install.packages('stringi')
          remotes::install_github("https://github.com/microsoft/finnts")
          install.packages('pkgdown')
          
        shell: Rscript {0}

      - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, branch = "gh-pages", github_pages = TRUE)'
